[CmdletBinding()]
param(
    [string]$OutputDirectory = 'output/performance/native-scale',
    [switch]$NoBuild,
    [switch]$Help
)

$ErrorActionPreference = 'Stop'

if ($Help) {
    @'
Usage:
  pwsh -File scripts/performance/measure-native-scale.ps1
  pwsh -File scripts/performance/measure-native-scale.ps1 -NoBuild

Runs the ignored release-only synthetic native benchmarks and writes redacted
JSON and Markdown under output/performance. The fixtures use new temporary
SQLite databases and generated bytes; they do not open the operator profile or
contact Google/YouTube.
'@
    exit 0
}

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$manifestPath = Join-Path $repositoryRoot 'src-tauri\Cargo.toml'
$resolvedOutputDirectory = [System.IO.Path]::GetFullPath(
    (Join-Path $repositoryRoot $OutputDirectory)
)
$allowedOutputRoot = [System.IO.Path]::GetFullPath(
    (Join-Path $repositoryRoot 'output\performance')
)
if (-not $resolvedOutputDirectory.StartsWith(
    $allowedOutputRoot + [System.IO.Path]::DirectorySeparatorChar,
    [System.StringComparison]::OrdinalIgnoreCase
)) {
    throw 'Native performance output must stay under output/performance.'
}

New-Item -ItemType Directory -Force -Path $resolvedOutputDirectory | Out-Null
$rawOutputPath = Join-Path $resolvedOutputDirectory 'native-scale-console.txt'
$jsonPath = Join-Path $resolvedOutputDirectory 'native-scale-baseline.json'
$markdownPath = Join-Path $resolvedOutputDirectory 'native-scale-baseline.md'

if ($NoBuild) {
    $testExecutable = Get-ChildItem (
        Join-Path $repositoryRoot 'src-tauri\target\release\deps\youtube_mass_uploader_lib-*.exe'
    ) -ErrorAction Stop |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1
    if (-not $testExecutable) {
        throw 'No release test executable exists. Run without -NoBuild first.'
    }
    $command = $testExecutable.FullName
    $commandArguments = @(
        'performance_benchmark', '--ignored', '--nocapture', '--test-threads=1'
    )
} else {
    $command = 'cargo'
    $commandArguments = @(
        'test', '--manifest-path', $manifestPath, '--release',
        'performance_benchmark', '--', '--ignored', '--nocapture',
        '--test-threads=1'
    )
}

$consoleLines = @(& $command @commandArguments 2>&1 | ForEach-Object { $_.ToString() })
$commandExitCode = $LASTEXITCODE
$consoleLines | Set-Content -LiteralPath $rawOutputPath -Encoding utf8
if ($commandExitCode -ne 0) {
    throw "Native performance benchmarks failed with exit code $commandExitCode."
}

$results = @(
    $consoleLines |
        ForEach-Object {
            if ($_ -match 'PERF_RESULT\s+(\{.+\})') {
                $Matches[1] | ConvertFrom-Json
            }
        }
)
if ($results.Count -eq 0) {
    throw 'No PERF_RESULT records were emitted by the native benchmarks.'
}
foreach ($result in $results) {
    if ($result.localOnly -ne $true) {
        throw 'A native performance record is missing the local-only guarantee.'
    }
}

$payload = [ordered]@{
    schemaVersion = 1
    localOnly = $true
    containsSensitiveData = $false
    application = [ordered]@{
        version = (Get-Content (Join-Path $repositoryRoot 'package.json') -Raw |
            ConvertFrom-Json).version
        buildProfile = 'release'
    }
    environment = [ordered]@{
        operatingSystem = [System.Environment]::OSVersion.VersionString
        architecture = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString()
        logicalProcessors = [System.Environment]::ProcessorCount
        totalPhysicalMemoryBytes = (Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory
    }
    fixture = [ordered]@{
        profile = 'synthetic-disposable'
        providerNetworkUsed = $false
        operatorProfileUsed = $false
    }
    results = $results
}

$json = $payload | ConvertTo-Json -Depth 8
foreach ($forbidden in @(
    'accessToken', 'refreshToken', 'oauthResponse', 'channelId', 'sourcePath',
    'fileName', 'mediaBytes', 'providerPayload'
)) {
    if ($json.Contains($forbidden, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Native performance output contains forbidden dimension $forbidden."
    }
}
$json | Set-Content -LiteralPath $jsonPath -Encoding utf8

$rows = foreach ($result in $results) {
    "| $($result.surface) | $($result.fixtureSize) | $($result.samples) | $($result.minimumMs) ms | $($result.p50Ms) ms | $($result.p95Ms) ms |"
}
$markdown = @(
    '# Native scale baseline',
    '',
    '- Local-only: yes',
    '- Sensitive data included: no',
    '- Build profile: release',
    '- Fixture profile: synthetic disposable databases and generated bytes',
    '',
    '| Surface | Fixture size | Samples | Minimum | p50 | p95 |',
    '| --- | ---: | ---: | ---: | ---: | ---: |',
    $rows
) -join [Environment]::NewLine
$markdown | Set-Content -LiteralPath $markdownPath -Encoding utf8

Write-Host "Native scale baseline written to $jsonPath and $markdownPath."
